# Docs
# @see: https://www.python-engineer.com/posts/run-python-github-actions/
# @see: https://github.com/actions/checkout
# @see: https://stackoverflow.com/questions/59319281/github-action-different-between-release-created-and-published

# This workflow converts the JSON /releases api response into XML format suitable for Drupal update checker
name: Release Feed | JSON to XML converter

on:
  release:
    types: [published]

jobs:
  run-script:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .github/releases-feed/nihod5
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          sparse-checkout: .github

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Maybe needed in the future
      #
      # - name: Install dependencies
      #   run: pip install -r requirements.txt
      #
      # not needed for now as every library needed
      # in the script already comes with Python

      - name: Run script
        run: python json2xml.py

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -a -m "GitHub Action | Updating XML release feed"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: 5.x.x 
